# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IK4gyktwCWoD7qvzg4pCyBexvTEXxRiv
"""

def sumar(a, b):
    return a + b
def es_par_o_impar(numero):
    if numero % 2 == 0:
        return "Par"
    else:
        return "Impar"
def saludar(nombre):
    return f"Hola, {nombre}!"
import math

def area_circulo(radio):
    return math.pi * radio ** 2
def tipo_numero(numero):
    if numero > 0:
        return "Positivo"
    elif numero < 0:
        return "Negativo"
    else:
        return "Cero"
def celsius_a_fahrenheit(celsius):
    return (celsius * 9/5) + 32
def cuadrado(numero):
    return numero ** 2
def factorial(n):
    if n < 0:
        return "No existe factorial para números negativos"
    resultado = 1
    for i in range(1, n + 1):
        resultado *= i
    return resultado
def contar_vocales(palabra):
    vocales = "aeiouAEIOU"
    return sum(1 for letra in palabra if letra in vocales)
def tabla_multiplicar(numero):
    for i in range(1, 11):
        print(f"{numero} x {i} = {numero * i}")
def area_triangulo(base, altura):
    return (base * altura) / 2

def area_rectangulo(base, altura):
    return base * altura

def menu_areas():
    while True:
        print("\nMenú de cálculo de áreas")
        print("1. Área de un círculo")
        print("2. Área de un triángulo")
        print("3. Área de un rectángulo")
        print("4. Salir")

        opcion = input("Seleccione una opción: ")

        if opcion == "1":
            radio = float(input("Ingrese el radio del círculo: "))
            print(f"Área del círculo: {area_circulo(radio):.2f}")
        elif opcion == "2":
            base = float(input("Ingrese la base del triángulo: "))
            altura = float(input("Ingrese la altura del triángulo: "))
            print(f"Área del triángulo: {area_triangulo(base, altura):.2f}")
        elif opcion == "3":
            base = float(input("Ingrese la base del rectángulo: "))
            altura = float(input("Ingrese la altura del rectángulo: "))
            print(f"Área del rectángulo: {area_rectangulo(base, altura):.2f}")
        elif opcion == "4":
            print("Saliendo del programa.")
            break
        else:
            print("Opción no válida. Intente de nuevo.")